node {
   stage 'Pull_Repository_from_GitHub'
	echo 'Repository pulled'
   stage 'Compile'
	echo 'Compilation is done'
   stage 'Unit_Test'
	echo 'Unit Testing is successful'
   stage 'Deploy Application to Dev Environment'
	echo 'Deploy is done'
   stage 'Func_Test'
	echo 'Functional Testing is successful'
   stage 'Deploy Application to Perf Environment'
	echo 'Deploy is done'
   stage 'Perf_Test'
	echo 'Performance Testing is successful'
   stage 'Deploy Application'
	echo 'Deploy is done'
   stage 'Execute JMeter Performance Tests'
	echo 'Performance Testing Testing is successful'
}
